
= What's this

This is the example for ** Firing Rules Using KIE Server Java Client API** which depicted in https://access.redhat.com/documentation/en-us/red_hat_jboss_brms/6.4/html-single/getting_started_guide/#firing_rules_using_maven and basic develop things related with BRMS.

== Setting Maven

Most of client development relies heavily on Maven, for example, the client use generated Model, KieScanner, etc.

Maven profile Configuration like

[source,xml]
----
<profile>
    <id>guvnor-m2-repo</id>
    <repositories>
        <repository>
          <id>guvnor-m2-repo</id>
          <name>BRMS Repository</name>
          <url>http://localhost:8080/business-central/maven2/</url>
          <layout>default</layout>
          <releases>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <updatePolicy>always</updatePolicy>
          </snapshots>
        </repository>
    </repositories>
</profile>
----

NOTE: The `updatePolicy` can be always", "daily" (default), "interval:XXX" (in minutes) or "never" (only if it doesn't exist locally).

It is either needed to turn on pre-emptive authentication for the repository server by

[source,xml]
----
<server>
    <id>guvnor-m2-repo</id>
    <username>kylin</username>
    <password>password1!</password>
    <configuration>
      <wagonProvider>httpclient</wagonProvider>
      <httpConfiguration>
        <all>
          <usePreemptive>true</usePreemptive>
        </all>
      </httpConfiguration>
    </configuration>
</server>
----

or set Authorization HTTP header with Base64 encoded credentials

[source,xml]
----
<server>
    <id>guvnor-m2-repo</id>
    <configuration>
      <httpHeaders>
        <property>
          <name>Authorization</name>
          <!-- Base64-encoded "kylin:password1!" -->
          <value>Basic a3lsaW46cGFzc3dvcmQxIQ==</value>
        </property>
      </httpHeaders>
    </configuration>
</server>
----

== Kie Server Fire Rules

[source,java]
----
Person p1 = new Person();
p1.setFirstName("Anton");
p1.setLastName("RedHat");
p1.setHourlyRate(11);
p1.setWage(20);
        
String url = "http://10.66.192.120:8080/kie-server/services/rest/server";
String username = "kylin";
String password = "password1!";
String container = "testContainer";
String session = "mySession";
        
KieServicesConfiguration config = KieServicesFactory.newRestConfiguration(url, username, password);
Set<Class<?>> allClasses = new HashSet<Class<?>>();
allClasses.add(Person.class);
config.addExtraClasses(allClasses);
        
KieServicesClient client  = KieServicesFactory.newKieServicesClient(config);
RuleServicesClient ruleClient = client.getServicesClient(RuleServicesClient.class);
List<GenericCommand<?>> commands = new ArrayList<GenericCommand<?>>();
        
commands.add((GenericCommand<?>) KieServices.Factory.get().getCommands().newInsert(p1,"Person Insert ID"));
commands.add((GenericCommand<?>) KieServices.Factory.get().getCommands().newFireAllRules("fire-identifier"));
        
BatchExecutionCommand batchCommand = KieServices.Factory.get().getCommands().newBatchExecution(commands,session);
ServiceResponse<ExecutionResults> response = ruleClient.executeCommandsWithResults(container, batchCommand);
System.out.println(response.getResult().getValue("fire-identifier"));
----

== Fire Rules Locally

[source,java]
----
KieServices kieServices = KieServices.Factory.get();
KieContainer kContainer = kieServices.getKieClasspathContainer();
KieBase kbase = kContainer.getKieBase("myBase");
KieSession ksession = kbase.newKieSession();
ksession.insert(person);
ksession.fireAllRules();
ksession.dispose();
----

== KieScanner

The `KieScanner` allows for continuous monitoring of the remote maven repository(http://10.10.10.10:8080/business-central/maven2/) to check if a new release of a Kie project has been installed(Build & Deploy in business-central). 
 
[source,java]
.*Example of KieScanner*
----
KieServices kieServices = KieServices.Factory.get();
ReleaseId releaseId = kieServices.newReleaseId( "com.redhat", "MyProject", "1.0" );
KieContainer kContainer = kieServices.newKieContainer(releaseId);
KieScanner kScanner = kieServices.newKieScanner( kContainer );
kScanner.start(1000 * 60 * 30);
----

