package travels;

import com.sample.domain.travel.Reservation;
import com.sample.domain.travel.Customer;
import com.sample.domain.travel.ClassUpgradeFee;

rule "GoldClassUpgrade"
    dialect "mvel"
    when
        Reservation(classUpgrade == true)
        Customer(loyaltyLevel == "Gold")
    then
        insertLogical(new ClassUpgradeFee(200.00));
end

rule "SilverClassUpgrade"
    dialect "mvel"
    when
        Reservation(classUpgrade == true)
        Customer(loyaltyLevel == "Silver")
    then
        insertLogical(new ClassUpgradeFee(300.00));
end

rule "BronzeClassUpgrade"
    dialect "mvel"
    when
        Reservation(classUpgrade == true)
        Customer(loyaltyLevel == "Bronze")
    then
        insertLogical(new ClassUpgradeFee(400.00));
end

rule "NoneClassUpgrade"
    dialect "mvel"
    when
        Reservation(classUpgrade == true)
        Customer(loyaltyLevel == "None")
    then
        insertLogical(new ClassUpgradeFee(500.00));
end

query "getUpgradeClassFees"
    Fee: ClassUpgradeFee();
end
