package travels;

import com.sample.domain.travel.Reservation;
import com.sample.domain.travel.Customer;
import com.sample.domain.travel.InsuranceFee;

rule "GoldInsuranceUpgrade"
    dialect "mvel"
    when
        Reservation(flightInsurance == true)
        Customer(loyaltyLevel == "Gold")
    then
        insertLogical(new InsuranceFee(20.00));
end

rule "SilverInsuranceUpgrade"
    dialect "mvel"
    when
        Reservation(flightInsurance == true)
        Customer(loyaltyLevel == "Silver")
    then
        insertLogical(new InsuranceFee(25.00));
end

rule "BronzeInsuranceUpgrade"
    dialect "mvel"
    when
        Reservation(flightInsurance == true)
        Customer(loyaltyLevel == "Bronze")
    then
        insertLogical(new InsuranceFee(30.00));
end

rule "NoneInsuranceUpgrade"
    dialect "mvel"
    when
        Reservation(flightInsurance == true)
        Customer(loyaltyLevel == "None")
    then
        insertLogical(new InsuranceFee(35.00));
end

query "getInsuranceFees"
    Fee: InsuranceFee();
end