apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
  labels:
    application: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
                                         
