apiVersion: v1
kind: Route
metadata:
  name: ${project.artifactId}
spec:
  host: ${project.artifactId}-rules-service.apps.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ${project.artifactId}
