jBPM 5.4 installation
---------------------

* install jboss-as-7.1.1.Final
. download, unzip
. deploy `drools-guvnor.war`
. deploy `designer.war`
. deploy `jbpm-gwt-console-server.war`
. deploy `jbpm-gwt-console.war`
. add `roles.properties`
. add `users.properties`  
. deploy `jbpm-human-task-war.war`
. deploy `jbpm-form-builder.war`

* install eclipse
. features/org.guvnor.tools.feature_5.5.0.Final.jar
. features/org.jbpm.eclipse.task.feature_5.5.0.Final.jar
. features/org.jbpm.eclipse.feature_5.5.0.Final.jar
. features/org.drools.eclipse.feature_5.5.0.Final.jar
. plugins/org.guvnor.tools_5.5.0.Final.jar
. plugins/org.jbpm.eclipse_5.5.0.Final.jar
. plugins/org.guvnor.eclipse.webdav_5.5.0.Final.jar
. plugins/org.jbpm.eclipse.task_5.5.0.Final.jar
. plugins/org.drools.eclipse_5.5.0.Final.jar


Configuring jBPM 5.4 to use Oracle Database 11g 
-----------------------------------------------

Introduction
^^^^^^^^^^^^

* jBPM 5.4 have three types of persistent entities 
. entities used for saving the the actual session, process and work item information.
. entities used for logging and generating Business Activity Monitoring (BAM) information.
. entities used by the task service.

* jBPM 5.4 have two different persistent units
. persistent units for jBPM and the logging/BAM information
. persistent units for the task service

Database setup
^^^^^^^^^^^^^^

Create 2 uses:

----
create tablespace JBPM5SPACE datafile '/oracle/oradata/JBPM5SPACE.DBF' size 100M;
create user jbpm54 identified by redhat default tablespace JBPM5SPACE;
grant connect,resource,dba to jbpm54;
----

Modify default `h2` parameter to `oracle` 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

* Change hibernate dialect

change defalt

----
<property name="hibernate.dialect" value="org.hibernate.dialect.H2Dialect"/>
----

to 

----
<property name="hibernate.dialect" value="org.hibernate.dialect.OracleDialect"/>
----

NOTE: both jbpm-gwt-console-server/WEB-INF/classes/META-INF/persistence.xml and jbpm-human-task-war/WEB-INF/classes/META-INF/persistence.xml has  dialect configration

* create datasource
Step 6 and Step 7 in https://github.com/kylinsoong/EJB/blob/master/docs/README.asciidoc

link:datasource-subsystem[Sample standalone-full.xml datasource subsystem]
